Name:           ros-melodic-tts
Version:        1.0.2
Release:        1%{?dist}
Summary:        ROS tts package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/tts
Source0:        %{name}-%{version}.tar.gz

Requires:       python2-boto3
Requires:       ros-melodic-actionlib-msgs
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-rospy
Requires:       ros-melodic-sound-play
Requires:       ros-melodic-std-msgs
BuildRequires:  python-mock
BuildRequires:  python2-boto3
BuildRequires:  ros-melodic-actionlib-msgs
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-rospy
BuildRequires:  ros-melodic-rostest
BuildRequires:  ros-melodic-rosunit
BuildRequires:  ros-melodic-sound-play
BuildRequires:  ros-melodic-std-msgs

%description
Package enabling a robot to speak with a human voice by providing a Text-To-
Speech ROS service

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Aug 01 2019 AWS RoboMaker <ros-contributions@amazon.com> - 1.0.2-1
- Autogenerated by Bloom

* Wed Mar 20 2019 AWS RoboMaker <ros-contributions@amazon.com> - 1.0.1-0
- Autogenerated by Bloom

